//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalizedConsoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalizedConsoleApp.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///File &apos;{0}&apos; was created in the {1} folder on &apos;{2}&apos;.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM-dd-yyyy_HH-mm-ss.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to close Application.
        /// </summary>
        internal static string ExitAppMessage {
            get {
                return ResourceManager.GetString("ExitAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name &apos;{0}&apos; matches the pattern of the folder {1}.
        /// </summary>
        internal static string FileInTargetFolder {
            get {
                return ResourceManager.GetString("FileInTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; property with the value &apos;{1}&apos; contains forbidden characters: &quot;&lt;&gt;?*\&quot;/|&quot;.
        /// </summary>
        internal static string HasForbiddenCharacters {
            get {
                return ResourceManager.GetString("HasForbiddenCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name for &apos;{0}&apos; matches the pattern for the folder {1}: {2}.
        /// </summary>
        internal static string MatchesPattern {
            get {
                return ResourceManager.GetString("MatchesPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; has been moved to {1}.
        /// </summary>
        internal static string MovedTo {
            get {
                return ResourceManager.GetString("MovedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name: {0}.
        /// </summary>
        internal static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no &apos;customSection&apos; in the config file.
        /// </summary>
        internal static string NoCustomSection {
            get {
                return ResourceManager.GetString("NoCustomSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} does not exist. Please create the directory to continue working with the application..
        /// </summary>
        internal static string NoDirectoryMessage {
            get {
                return ResourceManager.GetString("NoDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name for &apos;{0}&apos; does not match any pattern and has been moved to Default folder.
        /// </summary>
        internal static string NotMatchPattern {
            get {
                return ResourceManager.GetString("NotMatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; property for an element in &apos;customSection&apos; is empty.
        /// </summary>
        internal static string PropertyIsEmpty {
            get {
                return ResourceManager.GetString("PropertyIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Renamed file &apos;{0}&apos;.
        /// </summary>
        internal static string Renamed {
            get {
                return ResourceManager.GetString("Renamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started watching folder &apos;{0}&apos; .
        /// </summary>
        internal static string WatchedFolder {
            get {
                return ResourceManager.GetString("WatchedFolder", resourceCulture);
            }
        }
    }
}
